# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Guild"
license = "MIT"
licenselink = "https://github.com/tattwamasi/hugo-guild-theme/blob/master/LICENSE.md"
description = "A basic guild website theme"
homepage = "https://github.com/tattwamasi/hugo-guild-theme/"
tags = ["game", "guild", "blog"]
features = ["html5", "css3"]
min_version = 0.18

[author]
  name = "Rob Arnold"
  homepage = "https://rob.loci.net"
