# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Guild"
license = "MIT"
licenselink = "https://github.com/tattwamasi/guild/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/tattwamasi/guild/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Rob Arnold (Tokotsi)"
  homepage = "https://rob.loci.net"
